# Generated by Django 5.2.1 on 2025-05-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('available', models.CharField(max_length=40)),
                ('about_me_one', models.TextField()),
                ('about_me_two', models.TextField()),
            ],
        ),
    ]
