# Generated by Django 5.2.1 on 2025-05-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0002_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologiesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('end_update', models.DateField()),
                ('view_code', models.CharField()),
                ('technologies', models.ManyToManyField(to='Base_App.technologieslist')),
            ],
        ),
    ]
