# Generated by Django 5.2.1 on 2025-05-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_alter_project_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('author', models.CharField()),
                ('name', models.CharField()),
                ('anio', models.DateField()),
                ('rights_reserved', models.CharField()),
            ],
        ),
    ]
