# Generated by Django 5.2.1 on 2025-05-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0005_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about_me_three',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(default='Desarrollador Backend'),
        ),
    ]
