# Generated by Django 5.2.1 on 2025-05-29 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0007_backendlist_toollist_skill_person_skill_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='skill_id',
        ),
    ]
