# Generated by Django 5.2.1 on 2025-05-29 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0008_remove_person_skill_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_backend',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='tool_backend',
        ),
        migrations.DeleteModel(
            name='ToolList',
        ),
        migrations.DeleteModel(
            name='BackendList',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
