# Generated by Django 5.2.1 on 2025-05-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0009_remove_skill_skill_backend_remove_skill_tool_backend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ToolList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tool_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_backend', models.ManyToManyField(related_name='skills_skill', to='Base_App.backendlist')),
                ('tool_backend', models.ManyToManyField(related_name='skills_tool', to='Base_App.backendlist')),
            ],
        ),
    ]
