# Generated by Django 5.2.1 on 2025-05-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0010_backendlist_toollist_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='tool_backend',
            field=models.ManyToManyField(related_name='skills_tool', to='Base_App.toollist'),
        ),
    ]
