# Generated by Django 5.2.1 on 2025-05-29 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0011_alter_skill_tool_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skill_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='Base_App.skill'),
            preserve_default=False,
        ),
    ]
