# Generated by Django 5.2.1 on 2025-05-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0012_person_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Skill'),
        ),
    ]
