# Generated by Django 5.2.1 on 2025-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0013_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendlist',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toollist',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
