# Generated by Django 5.2.1 on 2025-05-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0014_backendlist_percentage_toollist_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
